### ISSUE TITLE
UB in MASKED_BBS's definition

### ISSUE THREAD

**Issue by koba-e964** [sugyan/yasai#16]
I'm not 100% sure that this is worth an issue, but this line causes undefined behavior. (`Bitboard` does not allow the `1 << 63`-bit to be set) 

https://github.com/sugyan/yasai/blob/0.4.0/src/bitboard/core.rs#L75

I'm planning to display warnings against such uses in future `shogi_core`.

**Comment by sugyan** [comment]
Thank you for pointing this out!
I changed it to create Bitboards after applying a mask in #18.
